insert into icon (file_name, name) values ('ORMobile/arrow_down_pressed_65px.png', 'Arrow Down Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_down_unpressed_65px.png', 'Arrow Down Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_left_pressed_65px.png', 'Arrow Left Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_left_unpressed_65px.png', 'Arrow Left Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_right_pressed_65px.png', 'Arrow Right Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_right_unpressed_65px.png', 'Arrow Right Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_up_pressed_65px.png', 'Arrow Up Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/arrow_up_unpressed_65px.png', 'Arrow Up Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/bg_paper_blue.jpg', 'Bg Paper Blue (Mobile)');
insert into icon (file_name, name) values ('ORMobile/bg_paper_white.jpg', 'Bg Paper White (Mobile)');
insert into icon (file_name, name) values ('ORMobile/bg_wall.png', 'Bg Wall (Mobile)');
insert into icon (file_name, name) values ('ORMobile/climate_cooling_58px.png', 'Climate Cooling (Mobile)');
insert into icon (file_name, name) values ('ORMobile/climate_coolingoff_58px.png', 'Climate Cooling Off (Mobile)');
insert into icon (file_name, name) values ('ORMobile/climate_heating_58px.png', 'Climate Heating (Mobile)');
insert into icon (file_name, name) values ('ORMobile/climate_heatingoff_58px.png', 'Climate Heating Off (Mobile)');
insert into icon (file_name, name) values ('ORMobile/colored_blue_52px.png', 'Colored Blue (Mobile)');
insert into icon (file_name, name) values ('ORMobile/colored_green_52px.png', 'Colored Green (Mobile)');
insert into icon (file_name, name) values ('ORMobile/colored_red_52px.png', 'Colored Red (Mobile)');
insert into icon (file_name, name) values ('ORMobile/colored_yellow_52px.png', 'Colored Yellow (Mobile)');
insert into icon (file_name, name) values ('ORMobile/divider_5px.png', 'Divider 5px (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_down_pressed_65px.png', 'Dpad Down Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_down_unpressed_65px.png', 'Dpad Down Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_left_pressed_65px.png', 'Dpad Left Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_left_unpressed_65px.png', 'Dpad Left Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_ok_pressed_65px.png', 'Dpad Ok Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_ok_unpressed_65px.png', 'Dpad Ok Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_right_pressed_65px.png', 'Dpad Right Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_right_unpressed_65px.png', 'Dpad Right Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_up_pressed_65px.png', 'Dpad Up Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/dpad_up_unpressed_65px.png', 'Dpad Up Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/feedback_large_260px.png', 'Feedback Large (Mobile)');
insert into icon (file_name, name) values ('ORMobile/feedback_small_260px.png', 'Feedback Small (Mobile)');
insert into icon (file_name, name) values ('ORMobile/flat_away_42px.png', 'Flat Away (Mobile)');
insert into icon (file_name, name) values ('ORMobile/flat_day_42px.png', 'Flat Day (Mobile)');
insert into icon (file_name, name) values ('ORMobile/flat_home_42px.png', 'Flat Home (Mobile)');
insert into icon (file_name, name) values ('ORMobile/flat_mic_42px.png', 'Flat Mic (Mobile)');
insert into icon (file_name, name) values ('ORMobile/flat_night_42px.png', 'Flat Night (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_button_pressed_78px.png', 'Generic Button Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_button_unpressed_78px.png', 'Generic Button Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_long_pressed_54px.png', 'Generic Long Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_long_unpressed_54px.png', 'Generic Long Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_slim_pressed_55px.png', 'Generic Slim Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/generic_slim_unpressed_55px.png', 'Generic Slim Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_audio_pressed_78px.png', 'Icon Audio Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_audio_unpressed_78px.png', 'Icon Audio Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_away_pressed_78px.png', 'Icon Away Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_away_unpressed_78px.png', 'Icon Away Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_blinds_pressed_78px.png', 'Icon Blinds Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_blinds_unpressed_78px.png', 'Icon Blinds Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_call_pressed_78px.png', 'Icon Call Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_call_unpressed_78px.png', 'Icon Call Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_cinema_pressed_78px.png', 'Icon Cinema Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_cinema_unpressed_78px.png', 'Icon Cinema Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_climate_pressed_78px.png', 'Icon Climate Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_climate_unpressed_78px.png', 'Icon Climate Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_day_pressed_78px.png', 'Icon Day Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_day_unpressed_78px.png', 'Icon Day Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_dinner_pressed_78px.png', 'Icon Dinner Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_dinner_unpressed_78px.png', 'Icon Dinner Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_doorclosed_pressed_78px.png', 'Icon Door Closed Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_doorclosed_unpressed_78px.png', 'Icon Door Closed Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_dooropen_pressed_78px.png', 'Icon Door Opened Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_dooropen_unpressed_78px.png', 'Icon Door Opened Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_floorplan_pressed_78px.png', 'Icon Floorplan Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_floorplan_unpressed_78px.png', 'Icon Floorplan Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_hangup_pressed_78px.png', 'Icon Hangup Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_hangup_unpressed_78px.png', 'Icon Hangup Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_home_pressed_78px.png', 'Icon Home Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_home_unpressed_78px.png', 'Icon Home Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_light_pressed_78px.png', 'Icon Light Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_light_unpressed_78px.png', 'Icon Light Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_mic_pressed_78px.png', 'Icon Mic Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_mic_unpressed_78px.png', 'Icon Mic Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_mute_pressed_78px.png', 'Icon Mute Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_mute_unpressed_78px.png', 'Icon Mute Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_night_pressed_78px.png', 'Icon Night Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_night_unpressed_78px.png', 'Icon Night Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_party_pressed_78px.png', 'Icon Party Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_party_unpressed_78px.png', 'Icon Party Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_relax_pressed_78px.png', 'Icon Relax Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_relax_unpressed_78px.png', 'Icon Relax Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_rooms_pressed_78px.png', 'Icon Rooms Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_rooms_unpressed_78px.png', 'Icon Rooms Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_security_pressed_78px.png', 'Icon Security Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_security_unpressed_78px.png', 'Icon Security Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_settings_pressed_78px.png', 'Icon Settings Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_settings_unpressed_78px.png', 'Icon Settings Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_shades_pressed_78px.png', 'Icon Shades Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_shades_unpressed_78px.png', 'Icon Shades Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_surround_pressed_78px.png', 'Icon Surround Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_surround_unpressed_78px.png', 'Icon Surround Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_volumedown_pressed_78px.png', 'Icon Volume Down Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_volumedown_unpressed_78px.png', 'Icon Volume Down Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_volumeup_pressed_78px.png', 'Icon Volume Up Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/icon_volumeup_unpressed_78px.png', 'Icon Volume Up Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/layout_options_pressed.png', 'Layout Options Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/layout_options_unpressed.png', 'Layout Options Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/layout_rooms_pressed.png', 'Layout Rooms Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/layout_rooms_unpressed.png', 'Layout Rooms Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/layout_topbar.png', 'Layout Topbar (Mobile)');
insert into icon (file_name, name) values ('ORMobile/peaceofmind_doorclosed_42px.png', 'Peace of Mind Door Closed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/peaceofmind_dooropen_42px.png', 'Peace of Mind Door Opened (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_forward_pressed_52px.png', 'Player Forward Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_forward_unpressed_52px.png', 'Player Forward Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_next_pressed_52px.png', 'Player Next Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_next_unpressed_52px.png', 'Player Next Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_pause_pressed_52px.png', 'Player Pause Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_pause_unpressed_52px.png', 'Player Pause Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_play_pressed_52px.png', 'Player Play Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_play_unpressed_52px.png', 'Player Play Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_previous_pressed_52px.png', 'Player Previous Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_previous_unpressed_52px.png', 'Player Previous Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_record_pressed_78px.png', 'Player Record Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_record_unpressed_78px.png', 'Player Record Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_rewind_pressed_52px.png', 'Player Rewind Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_rewind_unpressed_52px.png', 'Player Rewind Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_stop_pressed_52px.png', 'Player Stop Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/player_stop_unpressed_52px.png', 'Player Stop Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/power_pressed_80px.png', 'Power Pressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/power_unpressed_80px.png', 'Power Unpressed (Mobile)');
insert into icon (file_name, name) values ('ORMobile/tab_cinema_25px.png', 'Tab Cinema (Mobile)');
insert into icon (file_name, name) values ('ORMobile/tab_climate_25px.png', 'Tab Climate (Mobile)');
insert into icon (file_name, name) values ('ORMobile/tab_light_25px.png', 'Tab Light (Mobile)');
insert into icon (file_name, name) values ('ORMobile/tab_security_25px.png', 'Tab Security (Mobile)');

insert into icon (file_name, name) values ('ORTablet/arrow_down_pressed_72px.png', 'Arrow Down Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_down_unpressed_72px.png', 'Arrow Down Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_left_pressed_72px.png', 'Arrow Left Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_left_unpressed_72px.png', 'Arrow Left Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_right_pressed_72px.png', 'Arrow Right Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_right_unpressed_72px.png', 'Arrow Right Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_up_pressed_72px.png', 'Arrow Up Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/arrow_up_unpressed_72px.png', 'Arrow Up Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/bg_wall_tablet.jpg', 'Bg Wall Tablet (Tablet)');
insert into icon (file_name, name) values ('ORTablet/climate_cooling_113px.png', 'Climate Cooling (Tablet)');
insert into icon (file_name, name) values ('ORTablet/climate_coolingoff_96px.png', 'Climate Cooling Off (Tablet)');
insert into icon (file_name, name) values ('ORTablet/climate_heating_113px.png', 'Climate Heating (Tablet)');
insert into icon (file_name, name) values ('ORTablet/climate_heatingoff_96px.png', 'Climate Heating Off (Tablet)');
insert into icon (file_name, name) values ('ORTablet/colored_blue_52px.png', 'Colored Blue (Tablet)');
insert into icon (file_name, name) values ('ORTablet/colored_green_52px.png', 'Colored Green (Tablet)');
insert into icon (file_name, name) values ('ORTablet/colored_red_52px.png', 'Colored Red (Tablet)');
insert into icon (file_name, name) values ('ORTablet/colored_yellow_52px.png', 'Colored Yellow (Tablet)');
insert into icon (file_name, name) values ('ORTablet/divider_4px.png', 'Divider 4px (Tablet)');
insert into icon (file_name, name) values ('ORTablet/divider_5px.png', 'Divider 5px (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_down_pressed_72px.png', 'Dpad Down Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_down_unpressed_72px.png', 'Dpad Down Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_left_pressed_72px.png', 'Dpad Left Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_left_unpressed_72px.png', 'Dpad Left Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_ok_pressed_72px.png', 'Dpad Ok Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_ok_unpressed_72px.png', 'Dpad Ok Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_right_pressed_72px.png', 'Dpad Right Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_right_unpressed_72px.png', 'Dpad Right Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_up_pressed_72px.png', 'Dpad Up Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/dpad_up_unpressed_72px.png', 'Dpad Up Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/feedback_large_680px.png', 'Feedback Large (Tablet)');
insert into icon (file_name, name) values ('ORTablet/feedback_large_border_680px.png', 'Feedback Large Border (Tablet)');
insert into icon (file_name, name) values ('ORTablet/feedback_small_680px.png', 'Feedback Small (Tablet)');
insert into icon (file_name, name) values ('ORTablet/flat_away_50px.png', 'Flat Away (Tablet)');
insert into icon (file_name, name) values ('ORTablet/flat_day_50px.png', 'Flat Day (Tablet)');
insert into icon (file_name, name) values ('ORTablet/flat_home_50px.png', 'Flat Home (Tablet)');
insert into icon (file_name, name) values ('ORTablet/flat_mic_50px.png', 'Flat Mic (Tablet)');
insert into icon (file_name, name) values ('ORTablet/flat_night_50px.png', 'Flat Night (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_button_pressed_87px.png', 'Generic Button Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_button_unpressed_87px.png', 'Generic Button Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_long_74px.png', 'Generic Long (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_long_unpressed_74px.png', 'Generic Long Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_slim_pressed_87px.png', 'Generic Slim Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/generic_slim_unpressed_87px.png', 'Generic Slim Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_audio_pressed_87px.png', 'Icon Audio Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_audio_unpressed_87px.png', 'Icon Audio Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_away_pressed_87px.png', 'Icon Away Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_away_unpressed_87px.png', 'Icon Away Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_blinds_pressed_87px.png', 'Icon Blinds Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_blinds_unpressed_87px.png', 'Icon Blinds Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_call_pressed_87px.png', 'Icon Call Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_call_unpressed_87px.png', 'Icon Call Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_cinema_pressed_87px.png', 'Icon Cinema Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_cinema_unpressed_87px.png', 'Icon Cinema Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_climate_pressed_87px.png', 'Icon Climate Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_climate_unpressed_87px.png', 'Icon Climate Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_day_pressed_87px.png', 'Icon Day Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_day_unpressed_87px.png', 'Icon Day Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_dinner_pressed_87px.png', 'Icon Dinner Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_dinner_unpressed_87px.png', 'Icon Dinner Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_doorclosed_pressed_87px.png', 'Icon Door Closed Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_doorclosed_unpressed_87px.png', 'Icon Door Closed Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_dooropen_pressed_87px.png', 'Icon Door Opened Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_dooropen_unpressed_87px.png', 'Icon Door Opened Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_floorplan_pressed_87px.png', 'Icon Floorplan Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_floorplan_unpressed_87px.png', 'Icon Floorplan Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_hangup_pressed_87px.png', 'Icon Hangup Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_hangup_unpressed_87px.png', 'Icon Hangup Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_home_pressed_87px.png', 'Icon Home Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_home_unpressed_87px.png', 'Icon Home Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_light_pressed_87px.png', 'Icon Light Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_light_unpressed_87px.png', 'Icon Light Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_mic_pressed_87px.png', 'Icon Mic Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_mic_unpressed_87px.png', 'Icon Mic Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_mute_pressed_87px.png', 'Icon Mute Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_mute_unpressed_87px.png', 'Icon Mute Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_night_pressed_87px.png', 'Icon Night Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_night_unpressed_87px.png', 'Icon Night Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_party_pressed_87px.png', 'Icon Party Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_party_unpressed_87px.png', 'Icon Party Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_relax_pressed_87px.png', 'Icon Relax Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_relax_unpressed_87px.png', 'Icon Relax Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_rooms_pressed_87px.png', 'Icon Rooms Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_rooms_unpressed_87px.png', 'Icon Rooms Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_security_pressed_87px.png', 'Icon Security Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_security_unpressed_87px.png', 'Icon Security Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_settings_pressed_87px.png', 'Icon Settings Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_settings_unpressed_87px.png', 'Icon Settings Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_shades_pressed_87px.png', 'Icon Shades Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_shades_unpressed_87px.png', 'Icon Shades Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_surround_pressed_87px.png', 'Icon Surround Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_surround_unpressed_87px.png', 'Icon Surround Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_volumedown_pressed_87px.png', 'Icon Volume Down Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_volumedown_unpressed_87px.png', 'Icon Volume Down Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_volumeup_pressed_87px.png', 'Icon Volume Up Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/icon_volumeup_unpressed_87px.png', 'Icon Volume Up Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/layout_sidebar_768px.png', 'Layout Sidebar (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_forward_pressed_52px.png', 'Player Forward Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_forward_unpressed_52px.png', 'Player Forward Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_next_pressed_52px.png', 'Player Next Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_next_unpressed_52px.png', 'Player Next Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_pause_pressed_52px.png', 'Player Pause Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_pause_unpressed_52px.png', 'Player Pause Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_play_pressed_52px.png', 'Player Play Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_play_unpressed_52px.png', 'Player Play Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_previous_pressed_52px.png', 'Player Previous Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_previous_unpressed_52px.png', 'Player Previous Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_record_pressed_78px.png', 'Player Record Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_record_unpressed_78px.png', 'Player Record Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_rewind_pressed_52px.png', 'Player Rewind Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_rewind_unpressed_52px.png', 'Player Rewind Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_stop_pressed_52px.png', 'Player Stop Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/player_stop_unpressed_52px.png', 'Player Stop Unpressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/power_pressed_87px.png', 'Power Pressed (Tablet)');
insert into icon (file_name, name) values ('ORTablet/power_unpressed_87px.png', 'Power Unpressed (Tablet)');

insert into icon (file_name, name) values ('slider_off_24px.png', 'Slider off');
insert into icon (file_name, name) values ('slider_on_24px.png', 'Slider on');
insert into icon (file_name, name) values ('OpenRemote.png', 'Open Remote');
